title: "The Joy of Coding: Episode Guide"
baseurl: /joy-of-coding-episode-guide

collections:
  episodes:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"

exclude:
  - CONTRIBUTE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/
  - utils/

livereload: true
incremental: true
